version: '3'
services:
  db:
    image: 'postgres:11'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tamingthymeleafdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
